version: '3.8'

services:
  db:
    image: postgres:16
    container_name: coincheck_db
    restart: always
    environment:
      POSTGRES_USER: hoge
      POSTGRES_PASSWORD: hoge
      POSTGRES_DB: coincheck_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

