CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    rate DOUBLE PRECISION NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    order_type VARCHAR(255) NOT NULL,
    pair VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
